# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Intentra < Formula
  desc "Deterministic AI-powered commit planning engine"
  homepage "https://github.com/crvgilbertson/intentra"
  version "0.5.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crvgilbertson/intentra/releases/download/v0.5.4/intentra_0.5.4_darwin_amd64.tar.gz"
      sha256 "eff512ae0e849a7a4dfa603f72dc41835a8e994e09ebd6086fe48769ad60de96"

      define_method(:install) do
        bin.install "intentra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crvgilbertson/intentra/releases/download/v0.5.4/intentra_0.5.4_darwin_arm64.tar.gz"
      sha256 "d47a35f0b4539e2b95ab567893df589e6493a3dece0be55abc55af8a8965c6c2"

      define_method(:install) do
        bin.install "intentra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/crvgilbertson/intentra/releases/download/v0.5.4/intentra_0.5.4_linux_amd64.tar.gz"
      sha256 "7dd2c15a93e858624233559a3a6ac0b4b5998b1ccda00eef26effc3dd2a30fda"
      define_method(:install) do
        bin.install "intentra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crvgilbertson/intentra/releases/download/v0.5.4/intentra_0.5.4_linux_arm64.tar.gz"
      sha256 "0efbea70fd7f1593c8731bf3fddb2cdb5f9371337f96b6532d0d3546dcb94e3f"
      define_method(:install) do
        bin.install "intentra"
      end
    end
  end
end
