# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Intentra < Formula
  desc "Deterministic AI-powered commit planning engine"
  homepage "https://github.com/crvgilbertson/intentra"
  version "0.5.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crvgilbertson/intentra/releases/download/v0.5.7/intentra_0.5.7_darwin_amd64.tar.gz"
      sha256 "cf1cf08d97ca6e8e47dd04da7ce547bb9d88c2d566f9baabeea6f8dd0e050abe"

      define_method(:install) do
        bin.install "intentra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crvgilbertson/intentra/releases/download/v0.5.7/intentra_0.5.7_darwin_arm64.tar.gz"
      sha256 "bb97189f27f7f498be18d93ff934a382936eb62794a866137b47350b337624e5"

      define_method(:install) do
        bin.install "intentra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/crvgilbertson/intentra/releases/download/v0.5.7/intentra_0.5.7_linux_amd64.tar.gz"
      sha256 "2fa6fa923980bf4cf7aece8316abdb688b9f860de4f10c50029c779e7ee456fb"
      define_method(:install) do
        bin.install "intentra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crvgilbertson/intentra/releases/download/v0.5.7/intentra_0.5.7_linux_arm64.tar.gz"
      sha256 "8f31bca5faff3a7615f77f56a29308317cd7ba4ccfabc63b8d669dc1cf634083"
      define_method(:install) do
        bin.install "intentra"
      end
    end
  end
end
