# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Intentra < Formula
  desc "Deterministic AI-powered commit planning engine"
  homepage "https://github.com/crvgilbertson/intentra"
  version "0.5.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crvgilbertson/intentra/releases/download/v0.5.6/intentra_0.5.6_darwin_amd64.tar.gz"
      sha256 "c2b9d3400998a3d2c155a8e5765e1e6d63580d063ce662721b5fd27a91f08af0"

      define_method(:install) do
        bin.install "intentra"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crvgilbertson/intentra/releases/download/v0.5.6/intentra_0.5.6_darwin_arm64.tar.gz"
      sha256 "8f3d7cd872e7ba1deed99e895d0013b406b28076907da9aefe438a155aecffbd"

      define_method(:install) do
        bin.install "intentra"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/crvgilbertson/intentra/releases/download/v0.5.6/intentra_0.5.6_linux_amd64.tar.gz"
      sha256 "b3c2342575550b314ff6e116c7b84deaa6507828ec862a19fb251a3df765ef17"
      define_method(:install) do
        bin.install "intentra"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crvgilbertson/intentra/releases/download/v0.5.6/intentra_0.5.6_linux_arm64.tar.gz"
      sha256 "a92956d791e97ab4289daac450da931bc9c442ca9a805815eae1f8712a3ac994"
      define_method(:install) do
        bin.install "intentra"
      end
    end
  end
end
