# This file was generated by GoReleaser. DO NOT EDIT.
cask "intentra" do
  name "intentra"
  desc "Deterministic AI-powered commit planning engine"
  homepage "https://github.com/crvgilbertson/intentra"
  version "0.6.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "intentra"

  on_macos do
    on_intel do
      url "https://github.com/crvgilbertson/intentra/releases/download/v#{version}/intentra_#{version}_darwin_amd64.tar.gz"
      sha256 "bb0dab1a3eefec53749f0d8744f819fec392abe209a302538457df9d942c3829"
    end
    on_arm do
      url "https://github.com/crvgilbertson/intentra/releases/download/v#{version}/intentra_#{version}_darwin_arm64.tar.gz"
      sha256 "d1ecb36647f52159b9b624456312a123e2c54c0a29ebcd60d22ffc1440d42b57"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/crvgilbertson/intentra/releases/download/v#{version}/intentra_#{version}_linux_amd64.tar.gz"
      sha256 "e3cf4a22043d83b29b997400718d7dac3e83f1dceddb84bb6a26512c987cd892"
    end
    on_arm do
      url "https://github.com/crvgilbertson/intentra/releases/download/v#{version}/intentra_#{version}_linux_arm64.tar.gz"
      sha256 "5b7eefbf133abdbe60b4208bfd5cf923dc2d0c154efce23d6de51f4d7ebbf733"
    end
  end

  # No zap stanza required
end
